apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dcmm4uv3l-java-quarkus 
  janus-idp.io/tekton: dcmm4uv3l-java-quarkus
  backstage.io/kubernetes-id: dcmm4uv3l-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dcmm4uv3l-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml